#SingleInstance force

;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
; Win---># ; Shift--->+ ; Ctrl--->^ ; Alt--->! ;
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;

;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
; Timer Task
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;

#Persistent
  #Include *i %A_ScriptDir%\..\timer.ahk
return

;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
; Script enable/disable/edit/reload
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;

^#l::
  DetectHiddenWindows, On

  WinGet, UniqueID, , %A_ScriptDir%\ScriptManager.ahk ahk_exe AutoHotkey.exe

  If %UniqueID% {
    WinClose, %A_ScriptDir%\ScriptManager.ahk ahk_exe AutoHotkey.exe
  } Else {
    Run, %A_AhkPath% %A_ScriptDir%\ScriptManager.ahk
  }
return

^#s::
  Suspend
  TrayTip, , AutoHotkey switch status, , 1
return

^#e:: Edit

^#r::
  TrayTip, , AutoHotkey reloading..., , 1
  Sleep, 1000
  Reload
return

^#i::
  DetectHiddenWindows, On

  WinGet, UniqueID, , %A_ScriptDir%\IntelliSense.ahk ahk_exe AutoHotkey.exe

  If %UniqueID% {
    WinClose, %A_ScriptDir%\IntelliSense.ahk ahk_exe AutoHotkey.exe
    TrayTip, , IntelliSense Stopped..., , 1
  } Else {
    Run, %A_AhkPath% %A_ScriptDir%\IntelliSense.ahk
    TrayTip, , IntelliSense Start..., , 1
  }
return

^#m::
  DetectHiddenWindows, On

  WinGet, UniqueID, , %A_ScriptDir%\Min2Tray.ahk ahk_exe AutoHotkey.exe

  If %UniqueID% {
    WinClose, %A_ScriptDir%\Min2Tray.ahk ahk_exe AutoHotkey.exe
    TrayTip, , Min2Tray Stopped..., , 1
  } Else {
    Run, %A_AhkPath% %A_ScriptDir%\Min2Tray.ahk
    TrayTip, , Min2Tray Start..., , 1
  }
return

;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
; Key Bindings
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;

^!z::Run www.autohotkey.com

~Ctrl::
  ; Double tap detection
  if (A_PriorHotkey <> "~Ctrl" or A_TimeSincePriorHotkey > 300)
  {
    KeyWait, Ctrl
    return
  }

  ; UAC is opened for WSL, WinClose may NOT working
  Run everything
return

#n::
  IfWinExist Untitled - Notepad
    WinActivate
  else
    Run Notepad
    WinWait Untitled - Notepad
    WinActivate
return

#x::
  RegRead, HiddenFiles_Status, HKEY_CURRENT_USER, Software\Microsoft\Windows\CurrentVersion\Explorer\Advanced, HideFileExt
  RegRead, HiddenFiles_Status, HKEY_CURRENT_USER, Software\Microsoft\Windows\CurrentVersion\Explorer\Advanced, Hidden

  If HiddenFiles_Status = 1
    RegWrite, REG_DWORD, HKEY_CURRENT_USER, Software\Microsoft\Windows\CurrentVersion\Explorer\Advanced, HideFileExt, 0
  Else
    RegWrite, REG_DWORD, HKEY_CURRENT_USER, Software\Microsoft\Windows\CurrentVersion\Explorer\Advanced, HideFileExt, 1

  If HiddenFiles_Status = 2
    RegWrite, REG_DWORD, HKEY_CURRENT_USER, Software\Microsoft\Windows\CurrentVersion\Explorer\Advanced, Hidden, 1
  Else
    RegWrite, REG_DWORD, HKEY_CURRENT_USER, Software\Microsoft\Windows\CurrentVersion\Explorer\Advanced, Hidden, 2

  WinGetClass, eh_Class,A
  If (eh_Class = "CabinetWClass")
    Send, {F5}
  Else
    PostMessage, 0x111, 28931,,, A
return

;#i::
;  SplitPath, A_AhkPath,, ahk_dir
;
;  tmpfile=%ahk_dir%\ahk_text_edit_in_vim.txt
;  WinGetTitle, active_title, A
;  clipboard =
;  Send ^a
;  Send ^c
;  ClipWait
;  FileDelete, %tmpfile%
;  FileAppend, %clipboard%, %tmpfile%
;  RunWait, gvim "%tmpfile%" +
;  FileRead, text, %tmpfile%
;  clipboard:=text
;  WinWait %active_title%
;  Send ^v
;return

^#f10::
  WinSet, Style, ^0xC00000, A
  WinSet, Style, ^0¡Á40000,  A
return

;^#b::
;  Drive, Eject
;  If A_TimeSinceThisHotkey < 1000
;    Drive, Eject, , 1
;return

^#h::
  RunWait, Notepad %A_ScriptDir%\..\hotstring.ahk
  Reload
return

^#k::
  RunWait, Notepad %A_ScriptDir%\..\hotkey.ahk
  Reload
return

;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
; Mouse Wheel up/down w/o activate the window
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;

;WheelUp::
;  MouseGetPos, , , id, control
;  WinGetClass, class, ahk_id %id%
;
;  If class not in vncviewer::DesktopWindow,rctrl_renwnd32,OpusApp,LyncConversationWindowClass
;    SendMessage, 0x115, 0, 0, %control%, ahk_id %id%
;  Else
;    Send, {WheelUp}
;return

;WheelDown::
;  MouseGetPos, , , id, control
;  WinGetClass, class, ahk_id %id%
;
;  If class not in vncviewer::DesktopWindow,rctrl_renwnd32,OpusApp,LyncConversationWindowClass
;    SendMessage, 0x115, 1, 0, %control%, ahk_id %id%
;  Else
;    Send, {WheelDown}
;return

;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
; HotString
;
; Remember NOT to store personal information into repository...
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;

:://date::
  SendInput %A_YYYY%-%A_MM%-%A_DD% %A_Hour%:%A_Min%:%A_Sec%
return

#Include *i %A_ScriptDir%\..\hotkey.ahk
#Include *i %A_ScriptDir%\..\hotstring.ahk
